Host hpc01
  Hostname hpc01.sci.hokudai.ac.jp
  User s-miyamoto
  LogLevel ERROR

Host hpc03
  Hostname hpc03.sci.hokudai.ac.jp
  User s-miyamoto
  LogLevel ERROR

Host 11-03-ubuntu-shared.lab
  Hostname 192.168.100.201
  User s-miyamoto
  LogLevel ERROR
