#!/usr/bin/env bash

# GitHub Personal Access Token
# https://github.com/settings/personal-access-tokens
export GITHUB_PERSONAL_ACCESS_TOKEN="$(secret-tool lookup service claude-mcp key github_personal_access_token)"

# Wayback Machine API Keys
# https://archive.org/account/s3.php
export WAYBACK_ACCESS_KEY="$(secret-tool lookup service claude-mcp key wayback_access_key)"
export WAYBACK_SECRET_KEY="$(secret-tool lookup service claude-mcp key wayback_secret_key)"

exec "$@"
