# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_veryl_global_optspecs
	string join \n quiet verbose trace completion= h/help V/version
end

function __fish_veryl_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_veryl_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_veryl_using_subcommand
	set -l cmd (__fish_veryl_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c veryl -n "__fish_veryl_needs_command" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_needs_command" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_needs_command" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_needs_command" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_needs_command" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_needs_command" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "new" -d 'Create a new project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "init" -d 'Create a new project in an existing directory'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "fmt" -d 'Format the current project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "check" -d 'Analyze the current project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "build" -d 'Build the target codes corresponding to the current project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "clean" -d 'Clean-up the current project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "update" -d 'Update dependencies'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "publish" -d 'Publish the current project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "migrate" -d 'Migrate breaking changes from the previous version'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "doc" -d 'Build the document corresponding to the current project'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "metadata" -d 'Dump metadata of the current packege'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "dump" -d 'Dump debug info'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "test" -d 'Execute tests'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "synth" -d 'Synthesize to a simple gate-level netlist and report area / critical path'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "translate" -d 'Translate SystemVerilog files into Veryl source'
complete -c veryl -n "__fish_veryl_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c veryl -n "__fish_veryl_using_subcommand new" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand new" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand new" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand new" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand new" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand new" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand init" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand init" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand init" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand init" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand init" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand init" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -l check -d 'Run fmt in check mode'
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand fmt" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand check" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand check" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand check" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand check" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand check" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand check" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand build" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand build" -l check -d 'Run build in check mode'
complete -c veryl -n "__fish_veryl_using_subcommand build" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand build" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand build" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand build" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand build" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand clean" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand clean" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand clean" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand clean" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand clean" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand clean" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand update" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand update" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand update" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand update" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand update" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand update" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand publish" -l bump -d 'Bump version' -r -f -a "major\t'Increment majoir version'
minor\t'Increment minor version'
patch\t'Increment patch version'"
complete -c veryl -n "__fish_veryl_using_subcommand publish" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand publish" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand publish" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand publish" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand publish" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c veryl -n "__fish_veryl_using_subcommand publish" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -l check -d 'Run fmt in check mode'
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand migrate" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand doc" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand doc" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand doc" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand doc" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand doc" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand doc" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -l format -d 'output format' -r -f -a "pretty\t''
json\t''"
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand metadata" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l syntax-tree -d 'output syntex tree'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l symbol-table -d 'output symbol table'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l namespace-table -d 'output namespace table'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l type-dag -d 'output type dag'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l file-dag -d 'output file dag'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l attribute-table -d 'output attribute table'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l unsafe-table -d 'output unsafe table'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l ir -d 'output IR'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand dump" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand test" -s t -l test -d 'Test name filter (substring match)' -r
complete -c veryl -n "__fish_veryl_using_subcommand test" -l sim -d 'Simulator' -r -f -a "verilator\t'Verilator'
vcs\t'Synopsys VCS'
dsim\t'Altair DSim'
vivado\t'AMD Vivado Simulator'"
complete -c veryl -n "__fish_veryl_using_subcommand test" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand test" -l wave -d 'Dump waveform'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l disable-jit -d 'Disable JIT compilation for native tests'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l disable-ff-opt -d 'Disable FF classification optimization (force all always_ff variables to FF)'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l ignored -d 'Run only ignored tests'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l include-ignored -d 'Run both ignored and non-ignored tests'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand test" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand test" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c veryl -n "__fish_veryl_using_subcommand test" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l top -d 'Top module name (overrides `synth.top` in Veryl.toml; otherwise inferred from the first user module)' -r
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l timing-paths -d 'Number of worst-delay endpoints to report when dumping timing (overrides `synth.timing_paths` in Veryl.toml)' -r
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l dump-ir -d 'Dump the gate-level IR (netlist of gates and flip-flops)'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l dump-timing -d 'Dump the critical path trace'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l dump-area -d 'Dump the per-cell-kind area breakdown'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l dump-power -d 'Dump the power estimate (leakage + dynamic breakdown)'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c veryl -n "__fish_veryl_using_subcommand synth" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l completion -d 'Generate tab-completion' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l stdout -d 'Write the result to stdout instead of writing files. Useful for piping or redirecting to a non-default path'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l strict -d 'Fail if any unsupported constructs are encountered'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l no-format -d 'Skip the Veryl formatter pass and emit the raw translator output'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l quiet -d 'No output printed to stdout'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l verbose -d 'Use verbose output'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -l trace -d 'Use trace output'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -s h -l help -d 'Print help'
complete -c veryl -n "__fish_veryl_using_subcommand translate" -s V -l version -d 'Print version'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "new" -d 'Create a new project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "init" -d 'Create a new project in an existing directory'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "fmt" -d 'Format the current project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "check" -d 'Analyze the current project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "build" -d 'Build the target codes corresponding to the current project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "clean" -d 'Clean-up the current project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "update" -d 'Update dependencies'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "publish" -d 'Publish the current project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "migrate" -d 'Migrate breaking changes from the previous version'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "doc" -d 'Build the document corresponding to the current project'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "metadata" -d 'Dump metadata of the current packege'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "dump" -d 'Dump debug info'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "test" -d 'Execute tests'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "synth" -d 'Synthesize to a simple gate-level netlist and report area / critical path'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "translate" -d 'Translate SystemVerilog files into Veryl source'
complete -c veryl -n "__fish_veryl_using_subcommand help; and not __fish_seen_subcommand_from new init fmt check build clean update publish migrate doc metadata dump test synth translate help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
